### ISSUE TITLE
Add  authoritative identification OID  on snmptraps collector examples

### ISSUE THREAD

**Issue by sacckth** [karimra/srl-snmp-traps#44]
Though some people may argue this is opinionated, some snmp trap collector implementations require to add as a second var bind the OID 1.3.6.1.6.3.1.1.4.1:
_The authoritative identification of the notification
currently being sent. This variable occurs as
the second varbind in every SNMPv2-Trap-PDU and
InformRequest-PDU._

Hence, following binding would be required in the trap examples to make this compatible:
```
  bindings:
    - oid: '"1.3.6.1.6.3.1.1.4.1.0"'
      type: objectID
      value: '".1.3.6.1.2.1.1.5"'
    - oid: '".1.3.6.1.2.1.1.5"'
      type: octetString
      value: $hostname
    #Other OIDS
```
